MiPrimerAplicacionWeb/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerAplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

MiPrimerAplicacionWeb/Controllers/SucursalController.cs
using MiPrimerAplicacionWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiPrimerAplicacionWeb.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index(SucursalCLS oSucursalCls)
        {
            List<SucursalCLS> listaSucursal =  null;
            string nombreSucursal = oSucursalCls.nombre;

            using (var bd = new BDPasajeEntities())
            { 
                if (oSucursalCls.nombre == null)
                {
              
                        listaSucursal = (from sucursal in bd.Sucursal
                                         where sucursal.BHABILITADO == 1
                                         select new SucursalCLS
                                         {
                                             iidsucursal = sucursal.IIDSUCURSAL,
                                             nombre = sucursal.NOMBRE,
                                             direccion = sucursal.DIRECCION,
                                             telefono = sucursal.TELEFONO,
                                             email = sucursal.EMAIL
                                         }).ToList();
              
                }
                else {

                    listaSucursal = (from sucursal in bd.Sucursal
                                     where sucursal.BHABILITADO == 1
                                     && sucursal.NOMBRE.Contains(nombreSucursal)
                                     select new SucursalCLS
                                     {
                                         iidsucursal = sucursal.IIDSUCURSAL,
                                         nombre = sucursal.NOMBRE,
                                         direccion = sucursal.DIRECCION,
                                         telefono = sucursal.TELEFONO,
                                         email = sucursal.EMAIL
                                     }).ToList();

                }
                
            }




            return View(listaSucursal);
        }





        public ActionResult Agregar()
        {

            return View();

        }


        public ActionResult Editar(int id)
        {
            SucursalCLS oSucursalCLS = new SucursalCLS();

            using (var bd = new BDPasajeEntities())
            {
                // con el "First" te devuelve un Objeto
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();
                oSucursalCLS.iidsucursal = oSucursal.IIDSUCURSAL;
                oSucursalCLS.nombre = oSucursal.NOMBRE;
                oSucursalCLS.direccion = oSucursal.DIRECCION;
                oSucursalCLS.telefono = oSucursal.TELEFONO;
                oSucursalCLS.email = oSucursal.EMAIL;
                oSucursalCLS.fechaapertura = (DateTime)oSucursal.FECHAAPERTURA;
            }
            return View(oSucursalCLS);

        }


        [HttpPost]
        public ActionResult Agregar(SucursalCLS oSucursalCLS)
        {
            int nroRegistrosEncontrados = 0;
            string nombreSucursal = oSucursalCLS.nombre;
            using (var bd = new BDPasajeEntities())
            {
                nroRegistrosEncontrados = bd.Sucursal.Where(p => p.NOMBRE.Equals(nombreSucursal)).Count();
            }

            if (!ModelState.IsValid || nroRegistrosEncontrados >= 1)
            {
                if (nroRegistrosEncontrados >= 1) oSucursalCLS.mensajeError = "La sucursal ya existe.";
                return View(oSucursalCLS);
            }
            else
            {
                using (var bd = new BDPasajeEntities())
                {
                    Sucursal oSucursal = new Sucursal();
                    oSucursal.NOMBRE = oSucursalCLS.nombre;
                    oSucursal.DIRECCION = oSucursalCLS.direccion;
                    oSucursal.TELEFONO = oSucursalCLS.telefono;
                    oSucursal.EMAIL = oSucursalCLS.email;
                    oSucursal.FECHAAPERTURA = oSucursalCLS.fechaapertura;
                    oSucursal.BHABILITADO = 1;
                    bd.Sucursal.Add(oSucursal);
                    bd.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult Editar(SucursalCLS oSucursalCLS)
        {
            int nroRegistrosEncontrados = 0;
            string nombreSucursal = oSucursalCLS.nombre;
            int idSucursal = oSucursalCLS.iidsucursal;
            using (var bd = new BDPasajeEntities())
            {
                nroRegistrosEncontrados = bd.Sucursal.Where(p=> p.NOMBRE.Equals(nombreSucursal) && !p.IIDSUCURSAL.Equals(idSucursal)).Count();
            }


                if (!ModelState.IsValid || nroRegistrosEncontrados >= 1)
                {
                    if (nroRegistrosEncontrados >= 1) oSucursalCLS.mensajeError = "La sucursal ya existe.";
                    return View(oSucursalCLS);
                }
                else
                {
                    using (var bd = new BDPasajeEntities())
                    {
                        Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(idSucursal)).First();
                        oSucursal.NOMBRE = oSucursalCLS.nombre;
                        oSucursal.DIRECCION = oSucursalCLS.direccion;
                        oSucursal.TELEFONO = oSucursalCLS.telefono;
                        oSucursal.EMAIL = oSucursalCLS.email;
                        oSucursal.FECHAAPERTURA = oSucursalCLS.fechaapertura;
                        bd.SaveChanges();
                    }

                }
            return RedirectToAction("Index");

        }


        [HttpPost]
        public ActionResult Eliminar(int iidsucursal)
        {
            SucursalCLS oSucursalCLS = new SucursalCLS();


            using (var bd = new BDPasajeEntities())
            {
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(iidsucursal)).First();
                oSucursal.BHABILITADO = 0;
                bd.SaveChanges();
            }

            return RedirectToAction("Index");


        }
    }
}

MiPrimerAplicacionWeb/Views/Sucursal/Agregar.cshtml
@using MiPrimerAplicacionWeb.Models
@model SucursalCLS
@{
    ViewBag.Title = "Agregar";
}


<h2>Agregar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post, new { @id = "frmAgregarSucursal" }))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model != null && Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                }
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaapertura)
                @Html.EditorFor(p => p.fechaapertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaapertura", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin: auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                <!--<input type="submit" class="btn btn-primary" value="Guardar" />-->
                @Html.ActionLink("Regresar", "Index", "Sucursal", null, new { @class = "btn btn-danger" })
            </div>

        }

    </div>
</div>
<script>

    

    function Agregar() {

        var frmAgregarSucursal = document.getElementById("frmAgregarSucursal");
        frmAgregarSucursal.submit();
    }

    /*
    var frmAgregarSucursal = document.getElementById("frmAgregarSucursal");

    frmAgregarSucursal.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas agregar una Sucursal?") == 1) {
            frmAgregarSucursal.submit();

        }
    }
    */

</script>

<!-- Modal Confirm-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Deseas agregar una Sucursal?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Agregar();">Guardar</button>
            </div>
        </div>
    </div>
</div>

MiPrimerAplicacionWeb/Views/Sucursal/Editar.cshtml
@using MiPrimerAplicacionWeb.Models
@model SucursalCLS
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Sucursal", FormMethod.Post, new { @id = "frmEditarSucursal" }))
        {
            <div>
                @Html.LabelFor(p => p.iidsucursal)
                @Html.TextBoxFor(p => p.iidsucursal, new { @class = "form-control", @readOnly = true })
            </div>
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" });
                }
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaapertura)
                @Html.EditorFor(p => p.fechaapertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaapertura", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin: auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                <!--<input type="submit" class="btn btn-primary" value="Guardar" />-->
                @Html.ActionLink("Regresar", "Index", "Sucursal", null, new { @class = "btn btn-danger" })
            </div>

        }

    </div>
</div>


<script>
    function Guardar() {
        var frmEditarSucursal = document.getElementById("frmEditarSucursal");
        frmEditarSucursal.submit();

    }
    
    /*
    var frmEditarSucursal = document.getElementById("frmEditarSucursal");
    frmEditarSucursal.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los cambios?") == 1) {
            frmEditarSucursal.submit();
        }
    }
    */
</script>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Deseas guardar los cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

MiPrimerAplicacionWeb/Views/Sucursal/Index.cshtml
@using MiPrimerAplicacionWeb.Models;
@model List<SucursalCLS>

@{
    ViewBag.Title = "Index";
}

<h2>Sucursal</h2>
@Html.ActionLink("Agregar", "Agregar", "Sucursal", null, new { @class = "btn btn-primary" })


@using (Html.BeginForm("Index", "Sucursal", FormMethod.Get, new { @id = "frmBusquedaSucursal" }))
{
        @Html.Label("Ingrese nombre de marca")
        @Html.TextBox("nombre")


        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <td>@Html.LabelFor(p => Model[0].iidsucursal)</td>
                    <td>@Html.LabelFor(p => Model[0].nombre)</td>
                    <td>@Html.LabelFor(p => Model[0].telefono)</td>
                    <td>@Html.LabelFor(p => Model[0].email)</td>
                    <td>@Html.LabelFor(p => Model[0].fechaapertura)</td>
                    <td width="5%">Operaciones</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.iidsucursal</td>
                        <td>@item.nombre</td>
                        <td>@item.telefono</td>
                        <td>@item.email</td>
                        <td>@item.fechaapertura</td>
                        <td>
                            @Html.ActionLink(" ", "Editar", "Sucursal", new { id = @item.iidsucursal }, new { @class = "glyphicon glyphicon-edit btn btn-primary" })

                            <button type="button" class="glyphicon glyphicon-trash  btn btn-danger" data-toggle="modal" data-target="#exampleModal" onclick="MostrarPopup(@item.iidsucursal)"></button>


                            @*@Html.ActionLink(" ", "Eliminar", "Sucursal", new { id = @item.iidsucursal }, new { @class = "glyphicon glyphicon-trash  btn btn-danger", @onclick = "Eliminar('" + @item.nombre + "')" })*@
                        </td>
                    </tr>
                }
            </tbody>

        </table>
}

@using (Html.BeginForm("Eliminar", "Sucursal", FormMethod.Post, new { @id = "frmEliminarSucursal" }))
{
    @Html.Hidden("iidsucursal");
}

<script>
    /*
    function Eliminar(nombre) {
        if (confirm("¿Esta seguro de eliminar la sucursal "+ nombre +"?")) {

        } else {
            event.preventDefault();
        }
    }
    */

    function MostrarPopup(id) {
        document.getElementById("iidsucursal").value = id;
    }

    function Eliminar() {
        var frmEliminarSucursal = document.getElementById("frmEliminarSucursal");
        frmEliminarSucursal.submit();
    }




    var nombre = document.getElementById("nombre");
    nombre.onkeyup = function ()
    {
        var frmBusquedaSucursal = document.getElementById("frmBusquedaSucursal");
        frmBusquedaSucursal.submit();
        document.getElementById("nombre").focus();
    }




</script>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Estas seguro de eliminar el Sucursal seleccionado?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" onclick="Eliminar()">Si</button>
            </div>
        </div>
    </div>
</div>