MiPrimerAplicacionWeb/Models/Bus.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerAplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
            this.Viaje = new HashSet<Viaje>();
        }
    
        public int IIDBUS { get; set; }
        public Nullable<int> IIDSUCURSAL { get; set; }
        public Nullable<int> IIDTIPOBUS { get; set; }
        public string PLACA { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
        public Nullable<int> IIDMODELO { get; set; }
        public Nullable<int> NUMEROFILAS { get; set; }
        public Nullable<int> NUMEROCOLUMNAS { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> IIDMARCA { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoBus TipoBus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viaje> Viaje { get; set; }
    }
}

MiPrimerAplicacionWeb/Controllers/BusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiPrimerAplicacionWeb.Models;

namespace MiPrimerAplicacionWeb.Controllers
{
    public class BusController : Controller
    {

        private BusCLS oBusVal;
        private bool buscarBus(BusCLS oBusCLS)
        {
            bool busquedaId = true;
            bool busquedaPlaca = true;
            bool busquedaMarca = true;
            bool busquedaModelo = true;
            bool busquedaTipoBus = true;
            bool busquedaSucursal = true;

            if (oBusVal.iidbus > 0)
                busquedaId = oBusCLS.iidbus.ToString().Contains(oBusVal.iidbus.ToString());

            if (oBusVal.placa != null)
                busquedaPlaca = oBusCLS.placa.ToString().Contains(oBusVal.placa.ToString());

            if (oBusVal.iidmarca > 0)
                busquedaMarca = oBusCLS.iidmarca.ToString().Contains(oBusVal.iidmarca.ToString());

            if (oBusVal.iidmodelo > 0)
                busquedaModelo = oBusCLS.iidmodelo.ToString().Contains(oBusVal.iidmodelo.ToString());

            if (oBusVal.iidtipobus > 0)
                busquedaTipoBus = oBusCLS.iidtipobus.ToString().Contains(oBusVal.iidtipobus.ToString());

            if (oBusVal.iidsucursal > 0)
                busquedaSucursal = oBusCLS.iidsucursal.ToString().Contains(oBusVal.iidsucursal.ToString());



            return (busquedaId && busquedaPlaca && busquedaMarca && busquedaModelo && busquedaTipoBus && busquedaSucursal);
        }


        // GET: Bus
        public ActionResult Index(BusCLS oBusCLS)
        {
            oBusVal = oBusCLS;

            List<BusCLS> listaBus = null;

            List<BusCLS> listaFiltrado = null;


            using (var bd = new BDPasajeEntities())
            {
                listarCombos();

                listaBus = (from bus in bd.Bus
                                 join sucursal in bd.Sucursal
                                 on bus.IIDSUCURSAL equals sucursal.IIDSUCURSAL
                                 join tipobus in bd.TipoBus
                                 on bus.IIDTIPOBUS equals tipobus.IIDTIPOBUS
                                 join modelo in bd.Modelo
                                 on bus.IIDMODELO equals modelo.IIDMODELO
                                 join marca in bd.Marca
                                 on bus.IIDMARCA equals marca.IIDMARCA
                            where bus.BHABILITADO == 1
                            select new BusCLS
                                 {
                                     iidbus = bus.IIDBUS,
                                     placa = bus.PLACA,
                                     // fechacompra = bus.FECHACOMPRA,
                                     // numerocolumnas = bus.NUMEROCOLUMNAS,
                                     // numerofilas = bus.NUMEROFILAS,
                                     descripcion = bus.DESCRIPCION,
                                     observacion = bus.OBSERVACION,
                                    nombreTipoBus = tipobus.NOMBRE,
                                    nombreSucursal = sucursal.NOMBRE,
                                    nombreModelo = modelo.NOMBRE,
                                    nombreMarca = marca.NOMBRE,
                                    iidmarca = (int)bus.IIDMARCA,
                                    iidmodelo = (int)bus.IIDMODELO,
                                    iidsucursal = (int)bus.IIDSUCURSAL,
                                    iidtipobus = (int)bus.IIDTIPOBUS

                            }).ToList();


                if (oBusCLS.iidbus == 0 && oBusCLS.placa == null && oBusCLS.iidmarca == 0 && oBusCLS.iidmodelo == 0 && oBusCLS.iidtipobus == 0 && oBusCLS.iidsucursal == 0)
                {
                    listaFiltrado = listaBus;
                }
                else
                {
                    Predicate<BusCLS> pred = new Predicate<BusCLS>(buscarBus);
                    listaFiltrado = listaBus.FindAll(pred);
                    
                }


            }

            return View(listaFiltrado);
        
        }






        public ActionResult Agregar()
        {
            listarCombos();
            return View();
        }



        [HttpPost]
        public ActionResult Agregar(BusCLS oBusCls)
        {


            int nroRegistrosEncontrados = 0;
            string placaBus = oBusCls.placa;

            using (var bd = new BDPasajeEntities())
            {
                nroRegistrosEncontrados = bd.Bus.Where(p => p.PLACA.Equals(placaBus)).Count();
            }

            
            if (!ModelState.IsValid || nroRegistrosEncontrados >= 1) {
                if (nroRegistrosEncontrados >= 1) oBusCls.mensajeError = "La placa del Bus ya existe.";
                listarCombos();
                return View(oBusCls);
            }
            else
            { 

                        using (var db = new BDPasajeEntities())
                        {
                            Bus oBus = new Bus();
                            oBus.IIDSUCURSAL = oBusCls.iidsucursal;
                            oBus.IIDMARCA = oBusCls.iidmarca;
                            oBus.IIDMODELO = oBusCls.iidmodelo;
                            oBus.IIDTIPOBUS = oBusCls.iidtipobus;
                            oBus.NUMEROFILAS = oBusCls.numerofilas;
                            oBus.NUMEROCOLUMNAS = oBusCls.numerocolumnas;
                            oBus.FECHACOMPRA = oBusCls.fechacompra;
                            oBus.PLACA = oBusCls.placa;
                            oBus.DESCRIPCION = oBusCls.descripcion;
                            oBus.OBSERVACION = oBusCls.observacion;
                            oBus.BHABILITADO = 1;

                            db.Bus.Add(oBus);
                            db.SaveChanges();
    }
                
            }
            return RedirectToAction("Index");



        }



        public ActionResult Editar(int id)
        {


            BusCLS oBusCLS = new BusCLS();

            using (var bd = new BDPasajeEntities())
            {
                listarCombos();
                // con el "First" te devuelve un Objeto
                Bus oBus = bd.Bus.Where(p => p.IIDBUS.Equals(id)).First();

                oBusCLS.iidbus = id;
                oBusCLS.iidsucursal = (int)oBus.IIDSUCURSAL;
                oBusCLS.iidmarca = (int)oBus.IIDMARCA;
                oBusCLS.iidmodelo = (int)oBus.IIDMODELO;
                oBusCLS.iidtipobus = (int)oBus.IIDTIPOBUS;
                oBusCLS.numerofilas = (int)oBus.NUMEROFILAS;
                oBusCLS.numerocolumnas = (int)oBus.NUMEROCOLUMNAS;
                oBusCLS.fechacompra = (DateTime)oBus.FECHACOMPRA;
                oBusCLS.placa = oBus.PLACA;
                oBusCLS.descripcion = oBus.DESCRIPCION;
                oBusCLS.observacion = oBus.OBSERVACION;
                
            }
            return View(oBusCLS);
        }

        [HttpPost]
        public ActionResult Editar(BusCLS oBusCLS)
        {

            int nroRegistrosEncontrados = 0;
            int iidbus = oBusCLS.iidbus;
            string placaBus = oBusCLS.placa;

            using (var bd = new BDPasajeEntities())
            {
                nroRegistrosEncontrados = bd.Bus.Where(p => p.PLACA.Equals(placaBus) && !p.IIDBUS.Equals(iidbus)).Count();
            }


            if (!ModelState.IsValid || nroRegistrosEncontrados >= 1)
            {
                if (nroRegistrosEncontrados >= 1) oBusCLS.mensajeError = "La placa del Bus ya existe.";
                listarCombos();
                return View(oBusCLS);
            }
            else
            {

                int idBus = oBusCLS.iidbus;
                using (var db = new BDPasajeEntities())
                {
                    Bus oBus = db.Bus.Where(p => p.IIDBUS.Equals(idBus)).First();
                    oBus.IIDSUCURSAL = oBusCLS.iidsucursal;
                    oBus.IIDMARCA = oBusCLS.iidmarca;
                    oBus.IIDMODELO = oBusCLS.iidmodelo;
                    oBus.IIDTIPOBUS = oBusCLS.iidtipobus;
                    oBus.NUMEROFILAS = oBusCLS.numerofilas;
                    oBus.NUMEROCOLUMNAS = oBusCLS.numerocolumnas;
                    oBus.FECHACOMPRA = oBusCLS.fechacompra;
                    oBus.PLACA = oBusCLS.placa;
                    oBus.DESCRIPCION = oBusCLS.descripcion;
                    oBus.OBSERVACION = oBusCLS.observacion;
                    db.SaveChanges();

                }
                
            }
            return RedirectToAction("Index");
        }





        public ActionResult Eliminar(int iidbus)
        {
            using (var db = new BDPasajeEntities())
            {
                Bus oBus = db.Bus.Where(p => p.IIDBUS.Equals(iidbus)).First();
                oBus.BHABILITADO = 0;
                db.SaveChanges();
                return RedirectToAction("Index");
            }


        }



        List<SelectListItem> lista;
        List<SelectListItem> listaTipoBus;
        private void listarComboTipoBus()
        {

            using (var bd = new BDPasajeEntities())
            {
                lista = (from tipobus in bd.TipoBus
                         where tipobus.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = tipobus.NOMBRE,
                             Value = tipobus.IIDTIPOBUS.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione --", Value = "0" });
                ViewBag.listaTipoBus = lista;
            }


        }





        List<SelectListItem> listaMarca;
        private void listarComboMarca()
        {

            using (var bd = new BDPasajeEntities())
            {
                lista = (from marca in bd.Marca
                         where marca.BHABILITADO == 1

MiPrimerAplicacionWeb/Views/Bus/Agregar.cshtml
@using MiPrimerAplicacionWeb.Models
@model BusCLS

@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> listaTipoBus = (List<SelectListItem>)ViewBag.listaTipoBus;
    List<SelectListItem> listaMarca = (List<SelectListItem>)ViewBag.listaMarca;
    List<SelectListItem> listaModelo = (List<SelectListItem>)ViewBag.listaModelo;
    List<SelectListItem> listaSucursal = (List<SelectListItem>)ViewBag.listaSucursal;
}

<h2>Agregar Bus</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Bus", FormMethod.Post,new { @id= "frmAgregarBus" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>BusCLS</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.iidsucursal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidsucursal", listaSucursal, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidsucursal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.iidtipobus, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidtipobus", listaTipoBus, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidtipobus, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.iidmodelo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidmodelo", listaModelo, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidmodelo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.iidmarca, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidmarca", listaMarca, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidmarca, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.placa, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.placa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.placa, "", new { @class = "text-danger" })
                        @if (Model != null && Model.mensajeError != null)
                        {
                            @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                        }
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fechacompra, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.fechacompra, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.fechacompra, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.numerofilas, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.numerofilas, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.numerofilas, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.numerocolumnas, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.numerocolumnas, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.numerocolumnas, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.observacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.observacion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.observacion, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                            Guardar
                        </button>
                        <!--<input type="submit" class="btn btn-primary" value="Guardar" />-->
                        @Html.ActionLink("Regresar", "Index", "Bus", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        }

    </div>
</div>


<script>

    function Agregar() {
        var frmAgregarBus = document.getElementById("frmAgregarBus");
        frmAgregarBus.submit();
    }

    /*
    var frmAgregarBus = document.getElementById("frmAgregarBus");
    frmAgregarBus.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas agregar una Marca?") == 1) {
            frmAgregarBus.submit();
        }
    }
    */

</script>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Deseas agregar una Bus?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding: 1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Agregar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

MiPrimerAplicacionWeb/Views/Bus/Editar.cshtml
@using MiPrimerAplicacionWeb.Models
@model BusCLS

@{
    ViewBag.Title = "Editar";
    List<SelectListItem> listaTipoBus = (List<SelectListItem>)ViewBag.listaTipoBus;
    List<SelectListItem> listaMarca = (List<SelectListItem>)ViewBag.listaMarca;
    List<SelectListItem> listaModelo = (List<SelectListItem>)ViewBag.listaModelo;
    List<SelectListItem> listaSucursal = (List<SelectListItem>)ViewBag.listaSucursal;
}

<h2>Editar</h2>


<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Bus", FormMethod.Post, new { @id = "frmEditarBus"}))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>BusCLS</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.iidbus, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.iidbus, new { htmlAttributes = new { @class = "form-control", @readOnly = true } })
                        @Html.ValidationMessageFor(model => model.iidbus, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.iidsucursal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidsucursal", listaSucursal, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidsucursal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.iidtipobus, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidtipobus", listaTipoBus, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidtipobus, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.iidmodelo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidmodelo", listaModelo, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidmodelo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.iidmarca, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("iidmarca", listaMarca, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.iidmarca, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.placa, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.placa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.placa, "", new { @class = "text-danger" })
                        @if (Model != null && Model.mensajeError != null)
                        {
                            @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                        }
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fechacompra, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.fechacompra, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.fechacompra, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.numerofilas, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.numerofilas, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.numerofilas, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.numerocolumnas, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.numerocolumnas, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.numerocolumnas, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.observacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.observacion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.observacion, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                            Guardar
                        </button>
                        <!--<input type="submit" class="btn btn-primary" value="Guardar" />-->
                        @Html.ActionLink("Regresar", "Index", "Bus", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        }

    </div>
</div>

<script>


    function Guardar() {
        var frmEditarBus = document.getElementById("frmEditarBus");
        frmEditarBus.submit();
    }

    /*
    var frmEditar = document.getElementById("frmEditarBus");
    frmEditarBus.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los cambios?") == 1) {
            frmEditarBus.submit();
        }
    }
    */


</script>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Deseas guardar los cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding: 1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>