MiPrimerAplicacionWeb/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerAplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDMARCA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

MiPrimerAplicacionWeb/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiPrimerAplicacionWeb.Models;

namespace MiPrimerAplicacionWeb.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index(MarcaCLS omarcaCLS)
        {

            // recepcion del campo de buscar
            string nombreMarca = omarcaCLS.nombre;

            List<MarcaCLS> listaMarca = null;
            using (var bd = new BDPasajeEntities())
            {
                if (omarcaCLS.nombre == null)
                {
                    listaMarca = (from marca in bd.Marca
                                  where marca.BHABILITADO == 1
                                  select new MarcaCLS
                                  {
                                      iidmarca = marca.IIDMARCA,
                                      nombre = marca.NOMBRE,
                                      descripcion = marca.DESCRIPCION
                                  }).ToList();

                }
                else {
                    listaMarca = (from marca in bd.Marca
                                  where marca.BHABILITADO == 1
                                  && marca.NOMBRE.Contains(nombreMarca)
                                  select new MarcaCLS
                                  {
                                      iidmarca = marca.IIDMARCA,
                                      nombre = marca.NOMBRE,
                                      descripcion = marca.DESCRIPCION
                                  }).ToList();
                }
            }                   
            return View(listaMarca);
        }







        public ActionResult Agregar()
        {
            return View();
        }




        public ActionResult Editar(int id)
        {

            MarcaCLS oMarcaCLS = new MarcaCLS();

            using (var bd = new BDPasajeEntities())
            {
                // con el "First" te devuelve un Objeto
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(id)).First();
                oMarcaCLS.iidmarca = oMarca.IIDMARCA;
                oMarcaCLS.nombre = oMarca.NOMBRE;
                oMarcaCLS.descripcion = oMarca.DESCRIPCION;
            }
            return View(oMarcaCLS);
        }



        
        [HttpPost]
        public ActionResult Agregar(MarcaCLS oMarcaCLS)
        {
            int nroRegistrosEncontrados = 0;
            string nombreMarca = oMarcaCLS.nombre;
            using (var bd = new BDPasajeEntities())
            {
                nroRegistrosEncontrados = bd.Marca.Where(p => p.NOMBRE.Equals(nombreMarca)).Count();
            }

            if (!ModelState.IsValid || nroRegistrosEncontrados >= 1)
            {
                if (nroRegistrosEncontrados >= 1) oMarcaCLS.mensajeError = "La marca ya existe";
                return View(oMarcaCLS);
            }
            else {
                using (var bd = new BDPasajeEntities())
                { 
                    Marca oMarca = new Marca();
                    oMarca.NOMBRE = oMarcaCLS.nombre;
                    oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                    oMarca.BHABILITADO = 1;
                    bd.Marca.Add(oMarca);
                    bd.SaveChanges();
                }

            }
            return RedirectToAction("Index");

        }




        [HttpPost]
        public ActionResult Editar(MarcaCLS oMarcaCLS)
        {
            int nroRegistrosEncontrados = 0;
            string nombreMarca = oMarcaCLS.nombre;
            int iidMarca = oMarcaCLS.iidmarca;
            using (var bd = new BDPasajeEntities())
            {
                nroRegistrosEncontrados = bd.Marca.Where(p => p.NOMBRE.Equals(nombreMarca) && !p.IIDMARCA.Equals(iidMarca)).Count();
            }

            if (!ModelState.IsValid|| nroRegistrosEncontrados>=1)
            {
                if (nroRegistrosEncontrados >= 1) oMarcaCLS.mensajeError = "La marca ya existe";
                return View(oMarcaCLS);
            }
            else
            {
                int idMarca = oMarcaCLS.iidmarca;
                using (var bd = new BDPasajeEntities())
                {
                    Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(idMarca)).First();
                    oMarca.NOMBRE = oMarcaCLS.nombre;
                    oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                    bd.SaveChanges();
                }

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Eliminar(int iidmarca)
        {

                using (var bd = new BDPasajeEntities())
                {
                    Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(iidmarca)).First();
                    oMarca.BHABILITADO = 0;
                    bd.SaveChanges();
                    return RedirectToAction("Index");
                }
        }









    }
}

MiPrimerAplicacionWeb/Views/Marca/Agregar.cshtml
@using MiPrimerAplicacionWeb.Models
@model MarcaCLS

@{
    ViewBag.Title = "Agregar";
}
<h2>Agregar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Marca", FormMethod.Post, new { @id = "frmAgregar" }))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model!=null && Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                }
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control" })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin: auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                <!--<input type="submit" class="btn btn-primary" value="Guardar" />-->
                @Html.ActionLink("Regresar", "Index", "Marca", null, new { @class = "btn btn-danger" })
            </div>

        }

    </div>
</div>

<script>

    function Agregar() {
        var frmAgregar = document.getElementById("frmAgregar");
        frmAgregar.submit();
    }

    /*
    var frmAgregar = document.getElementById("frmAgregar");
    frmAgregar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas agregar una Marca?") == 1) {
            frmAgregar.submit();
        }
    }
    */

</script>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Deseas agregar una Marca?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding: 1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Agregar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

MiPrimerAplicacionWeb/Views/Marca/Editar.cshtml
@using MiPrimerAplicacionWeb.Models
@model MarcaCLS

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Marca", FormMethod.Post, new { @id = "frmEditar" }))
        {
            <div>
                @Html.LabelFor(p => p.iidmarca)
                @Html.TextBoxFor(p => p.iidmarca, new { @class = "form-control", @readOnly = true })
            </div>

            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model != null && Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" });
                }
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control" })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin: auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                <!--<input type="submit" class="btn btn-primary" value="Guardar" />-->
                @Html.ActionLink("Regresar", "Index", "Marca", null, new { @class = "btn btn-danger" })
            </div>

        }

    </div>
</div>



<script>
    function Guardar() {
        var frmEditar = document.getElementById("frmEditar");
        frmEditar.submit();
    }

    /*
    var frmEditar = document.getElementById("frmEditar");
    frmEditar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los cambios?") == 1) {
            frmEditar.submit();
        }
    }
    */
</script>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Deseas guardar los cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding: 1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

MiPrimerAplicacionWeb/Views/Marca/Index.cshtml
@using MiPrimerAplicacionWeb.Models;
@model List<MarcaCLS>

@{
    ViewBag.Title = "Index";
}

<h2>Marca</h2>

@Html.ActionLink("Agregar", "Agregar", "Marca", null, new { @class = "btn btn-primary" })


@using (Html.BeginForm("Index", "Marca", FormMethod.Post))
{
    @Html.Label("Ingrese nombre de marca")
    @Html.TextBox("nombre")
    <input type="submit" class="btn btn-success" value="Buscar" />

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td width="10%">@Html.LabelFor(p => Model[0].iidmarca)</td>
                <td width="20%">@Html.LabelFor(p => Model[0].nombre)</td>
                <td width="60%">@Html.LabelFor(p => Model[0].descripcion)</td>
                <td width="10%">Operaciones</td>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.iidmarca</td>
                    <td>@item.nombre</td>
                    <td>@item.descripcion</td>
                    <td>
                        @Html.ActionLink(" ", "Editar", "Marca", new { id = @item.iidmarca }, new { @class = "glyphicon glyphicon-edit btn btn-primary" })

                        <button type="button" class="glyphicon glyphicon-trash  btn btn-danger" data-toggle="modal" data-target="#exampleModal" onclick="MostrarPopup(@item.iidmarca)"></button>


                        @*@Html.ActionLink(" ", "Eliminar", "Marca", new { id = @item.iidmarca }, new { @class = "glyphicon glyphicon-trash  btn btn-danger", @onclick = "Eliminar('" + @item.nombre + "')" })*@


                    </td>
                </tr>
            }

        </tbody>

    </table>
}

@using (Html.BeginForm("Eliminar", "Marca", FormMethod.Post, new { @id = "frmEliminar" }))
{
    @Html.Hidden("iidmarca");
}


<script>

    function MostrarPopup(id) {
        document.getElementById("iidmarca").value = id
        // document.getElementById("titleModal").innerText = '¿Deseas eliminar la Marca ' + nombre + '?'
    }

    function Eliminar() {
        var frmEliminar = document.getElementById("frmEliminar");
        frmEliminar.submit();
    }

    /*
    function Eliminar(nombre) {
        if (confirm("¿Esta seguro de eliminar la marca " + nombre + "?")) {

        } else {
            event.preventDefault();
        }
    }
    */

</script>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Estas seguro de eliminar el Marca seleccionado?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" onclick="Eliminar()">Si</button>
            </div>
        </div>
    </div>
</div>