MiPrimerAplicacionWeb/Models/Viaje.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerAplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.Asiento = new HashSet<Asiento>();
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
        }
    
        public int IIDVIAJE { get; set; }
        public Nullable<int> IIDLUGARORIGEN { get; set; }
        public Nullable<int> IIDLUGARDESTINO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> FECHAVIAJE { get; set; }
        public Nullable<int> IIDBUS { get; set; }
        public Nullable<int> NUMEROASIENTOSDISPONIBLES { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public byte[] FOTO { get; set; }
        public string nombrefoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual Lugar Lugar1 { get; set; }
    }
}

MiPrimerAplicacionWeb/Controllers/ViajeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiPrimerAplicacionWeb.Models;

namespace MiPrimerAplicacionWeb.Controllers
{
    public class ViajeController : Controller
    {
        // GET: Viaje
        public ActionResult Index()
        {
            List<ViajeCLS> listaViaje = null;
            using (var bd = new BDPasajeEntities())
            {


                listaViaje = (from viaje in bd.Viaje
                            join lugarOrigen in bd.Lugar
                            on viaje.IIDLUGARORIGEN equals lugarOrigen.IIDLUGAR
                            join lugarDestino in bd.Lugar
                            on viaje.IIDLUGARDESTINO equals lugarDestino.IIDLUGAR
                              join bus in bd.Bus
                            on viaje.IIDBUS equals bus.IIDBUS

                              select new ViajeCLS
                            {
                                iidViaje = viaje.IIDVIAJE,
                                // precio = viaje.PRECIO,
                                // fechaViaje = bus.FECHAVIAJE,
                                nombreBus = bus.PLACA,
                                nombreLugarOrigen = lugarOrigen.NOMBRE,
                                nombreLugarDestino = lugarDestino.NOMBRE
                               

                            }).ToList();
            }

            return View(listaViaje);


        }



        public ActionResult Agregar()
        {
            listarCombos();
            return View();
        }


        public ActionResult Editar()
        {
            return View();
        }






        List<SelectListItem> lista;
        List<SelectListItem> listaLugar;
        private void listarComboLugar()
        {

            using (var bd = new BDPasajeEntities())
            {
                lista = (from lugar in bd.Lugar
                         where lugar.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = lugar.NOMBRE,
                             Value = lugar.IIDLUGAR.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione --", Value = "" });
                ViewBag.listaLugar = lista;
            }


        }




        List<SelectListItem> listaBus;
        private void listarComboBus()
        {

            using (var bd = new BDPasajeEntities())
            {
                lista = (from bus in bd.Bus
                         where bus.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = bus.PLACA,
                             Value = bus.IIDBUS.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione --", Value = "" });
                ViewBag.listaBus = lista;
            }


        }


        public void listarCombos()
        {
            listarComboLugar();
            listarComboBus();
        }


    }
}

MiPrimerAplicacionWeb/Views/Viaje/Agregar.cshtml
@model MiPrimerAplicacionWeb.Models.ViajeCLS

@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> listaBus = (List<SelectListItem>)ViewBag.listaBus;
    List<SelectListItem> listaLugar = (List<SelectListItem>)ViewBag.listaLugar;
}

<h2>Agregar</h2>



@using (Html.BeginForm("Agregar", "Viaje", FormMethod.Post, new { @id = "frmAgregarViaje" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ViajeCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarOrigen", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarDestino", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidBus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidBus", listaBus, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidBus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaViaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaViaje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaViaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numeroAsientosDisponibles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroAsientosDisponibles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroAsientosDisponibles, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                <!--<input type="submit" value="Create" class="btn btn-default" />-->
                @Html.ActionLink("Regresar", "Index", "Viaje", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

    <script>
        function Agregar() { 
            var frmAgregarViaje = document.getElementById("frmAgregarViaje");
            frmAgregarViaje.submit();
        }

    </script>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Desea Agregar un viaje?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding: 1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Agregar()" >Guardar</button>
            </div>
        </div>
    </div>
</div>

MiPrimerAplicacionWeb/Views/Viaje/Index.cshtml
@using MiPrimerAplicacionWeb.Models
@model List<ViajeCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Agregar", "Agregar", "Viaje", null, new { @class = "btn btn-primary" })
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <td>@Html.LabelFor(p => Model[0].iidViaje)</td>
            <td>@Html.LabelFor(p => Model[0].nombreBus)</td>
            <td>@Html.LabelFor(p => Model[0].nombreLugarOrigen)</td>
            <td>@Html.LabelFor(p => Model[0].nombreLugarDestino)</td>
            <td width="10%">Operaciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.iidViaje</td>
                <td>@item.nombreBus</td>
                <td>@item.nombreLugarOrigen</td>
                <td>@item.nombreLugarDestino</td>
                <td>
                    @Html.ActionLink(" ", "Editar", "Viaje", new { id = @item.iidViaje }, new { @class = "glyphicon glyphicon-edit btn btn-primary" })
                    @Html.ActionLink(" ", "Elimninar", "Viaje", new { id = @item.iidViaje }, new { @class = "glyphicon glyphicon-trash  btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>